#!/bin/bash
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail

# Mixar Build Script
# Builds Blender (always Release) + Mixar (environment from settings.sh)

# Load all settings from settings.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/settings.sh"

# Use MIXAR_ENV directly from settings.sh (already exported there)
# Blender always builds in Release mode for optimal performance
BLENDER_BUILD_ENV="Release"

# Define build directory for this environment
BUILD_ENV_DIR="${BUILD_DIR}/${MIXAR_ENV}"

# Overlay Mixar sources onto source
echo "Overlaying Mixar sources onto source..."
"$SCRIPT_DIR/overlay.sh"

# Configure build directory
mkdir -p "${BUILD_ENV_DIR}"

# Generate environment configuration header
echo "Generating environment configuration for: $MIXAR_ENV"
mkdir -p "$SOURCE_DIR/source/creator"
cat > "$SOURCE_DIR/source/creator/mixar_env_config.h" << EOF
#pragma once
// Auto-generated file - DO NOT EDIT
// Generated for environment: $MIXAR_ENV

#define MIXAR_BASE_URL "$MIXAR_BACKEND_URL"
#define MIXAR_FRONTEND_BASE_URL "$MIXAR_FRONTEND_URL"
#define MIXAR_CURRENT_ENV "$MIXAR_ENV"

// Environment-specific macros for conditional compilation
EOF

# Generate environment-specific macro based on current MIXAR_ENV
case "$MIXAR_ENV" in
    "Prod")
        echo "#define MIXAR_ENV_PROD" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    "Dev")
        echo "#define MIXAR_ENV_DEV" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    "UAT"|"Uat")
        echo "#define MIXAR_ENV_UAT" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    *)
        echo "#define MIXAR_ENV_PROD  // Default to production for unknown environment" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
esac

# Emit the build-frozen Python env marker (mirrors mixar_env_config.h on the
# Python side). Used by mixar.config.config.get_dev_bypass_credentials() to
# gate the dev bypass behind a value that cannot be flipped by editing the
# bundled mixar.json. Only Dev builds get DEV_BYPASS_ALLOWED=True.
if [ "$MIXAR_ENV" = "Dev" ]; then
    BUILD_ENV_DEV_BYPASS="True"
else
    BUILD_ENV_DEV_BYPASS="False"
fi
mkdir -p "$SOURCE_DIR/scripts/mixar/config"
cat > "$SOURCE_DIR/scripts/mixar/config/_build_env.py" << EOF
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
# SPDX-License-Identifier: GPL-2.0-or-later
# Auto-generated by scripts/unix/build.sh - DO NOT EDIT
BUILD_ENVIRONMENT = "$MIXAR_ENV"
DEV_BYPASS_ALLOWED = $BUILD_ENV_DEV_BYPASS
EOF

# Configure with CMake (all platform logic handled in settings.sh)
echo "Configuring Mixar build - Blender: $BLENDER_BUILD_ENV, Mixar Environment: $MIXAR_ENV for $PLATFORM..."
cmake -C "$CMAKE_DIR/mixar_overrides.cmake" \
    $CMAKE_GENERATOR_ARGS \
    -S "$SOURCE_DIR" \
    -B "$BUILD_ENV_DIR" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE="$BLENDER_BUILD_ENV"

# Build (all platform-specific args handled in settings.sh)
echo "Building Blender in $BLENDER_BUILD_ENV mode for Mixar environment: $MIXAR_ENV"
echo "Using $BUILD_CORES cores for parallel build"
cmake --build "$BUILD_ENV_DIR" $BUILD_ARGS
cmake --build "$BUILD_ENV_DIR" --target install --config "$BLENDER_BUILD_ENV"

# Generate runtime configuration for the bundle
echo "Generating runtime configuration for bundle..."
if [[ "$PLATFORM" == "macOS" ]]; then
    BUNDLE_CONFIG_DIR="$BUILD_ENV_DIR/bin/Mixar.app/Contents/Resources/$BLENDER_VERSION/config"
elif [[ "$PLATFORM" == "Linux" ]]; then
    BUNDLE_CONFIG_DIR="$BUILD_ENV_DIR/bin/$BLENDER_VERSION/config"
else
    echo "Error: Unsupported platform for config generation: $PLATFORM" >&2
    exit 1
fi
python3 "$ROOT_DIR/scripts/generate_config.py" --output "$BUNDLE_CONFIG_DIR/mixar.json"

# Install Python packages using the generated Python binary
echo "Installing Python packages for Mixar..."

# Determine base path for embedded Python based on platform
if [[ "$PLATFORM" == "macOS" ]]; then
    PY_BASE="$BUILD_ENV_DIR/bin/Mixar.app/Contents/Resources"
elif [[ "$PLATFORM" == "Linux" ]]; then
    PY_BASE="$BUILD_ENV_DIR/bin"
else
    echo "Error: Unsupported platform: $PLATFORM"
    exit 1
fi

# Try common python binary names inside Blender's embedded Python
PYTHON_BIN=""
for candidate in \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python${PYTHON_VERSION}" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python3" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python"; do
    if [[ -x "$candidate" ]]; then
        PYTHON_BIN="$candidate"
        break
    fi
done

SITE_PACKAGES="$PY_BASE/$BLENDER_VERSION/python/lib/python${PYTHON_VERSION}/site-packages"
REQUIREMENTS_FILE="$(dirname "$SCRIPT_DIR")/python_requirements.txt"

if [[ -n "$PYTHON_BIN" ]]; then
    echo "Found Python binary: $PYTHON_BIN"
    mkdir -p "$SITE_PACKAGES"
    
    # Check if requirements file exists
    if [[ -f "$REQUIREMENTS_FILE" ]]; then
        echo "Installing packages from: $REQUIREMENTS_FILE"
        
        # Force pip to install to the embedded Python's site-packages
        # Use --no-user to prevent installation to user site-packages
        # Use --target to specify the exact location
        if "$PYTHON_BIN" -m pip install --no-user --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
            echo "Successfully installed Python packages to embedded Python site-packages"
        elif command -v pip3 >/dev/null 2>&1; then
            echo "Embedded pip failed, trying system pip with --target..."
            if pip3 install --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
                echo "Successfully installed Python packages using system pip"
            else
                echo "Warning: Failed to install Python packages from requirements file"
            fi
        else
            echo "Warning: No pip available, skipping Python package installation"
        fi
    else
        echo "Warning: Requirements file not found at: $REQUIREMENTS_FILE"
        exit 1
    fi
else
    echo "Warning: Python binary not found under: $PY_BASE/$BLENDER_VERSION/python/bin"
fi

# Done
# Print platform-appropriate launch command
if [[ "$PLATFORM" == "macOS" ]]; then
    MIXAR_BIN="$BUILD_ENV_DIR/bin/Mixar.app/Contents/MacOS/Mixar"
elif [[ "$PLATFORM" == "Linux" ]]; then
    MIXAR_BIN="$BUILD_ENV_DIR/bin/mixar"
else
    MIXAR_BIN="$BUILD_ENV_DIR/bin/mixar"
fi

echo "=== Build Complete ==="
echo "Python packages installed from: $REQUIREMENTS_FILE"
echo "Run Mixar using: $MIXAR_BIN"
